import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2 className="mx-5 bg-slate-400 text-3xl my-4">Hey This is Home Page</h2>
      </main>

    </div>
  )
}
